[package]
name = "resl-macros"
description = "Implements the procedural macros used by the RESL standard library"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }

[dependencies.syn]
workspace = true
features = [
    "full"
]
